# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tourisme.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1080, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.search = QtGui.QWidget(self.centralwidget)
        self.search.setEnabled(True)
        self.search.setVisible(False)
        self.search.setGeometry(QtCore.QRect(160, 60, 761, 221))
        self.search.setObjectName(_fromUtf8("search"))
        self.line_2 = QtGui.QFrame(self.search)
        self.line_2.setGeometry(QtCore.QRect(10, 120, 21, 51))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.s_arrdt = QtGui.QSpinBox(self.search)
        self.s_arrdt.setGeometry(QtCore.QRect(440, 130, 131, 31))
        self.s_arrdt.setMinimum(75001)
        self.s_arrdt.setMaximum(75099)
        self.s_arrdt.setObjectName(_fromUtf8("s_arrdt"))
        self.box_velib = QtGui.QCheckBox(self.search)
        self.box_velib.setGeometry(QtCore.QRect(220, 130, 111, 31))
        self.box_velib.setObjectName(_fromUtf8("box_velib"))
        self.s_go = QtGui.QPushButton(self.search)
        self.s_go.setGeometry(QtCore.QRect(630, 130, 111, 31))
        self.s_go.setObjectName(_fromUtf8("s_go"))
        self.box_tournages = QtGui.QCheckBox(self.search)
        self.box_tournages.setGeometry(QtCore.QRect(30, 130, 151, 31))
        self.box_tournages.setObjectName(_fromUtf8("box_tournages"))
        self.box_wifi = QtGui.QCheckBox(self.search)
        self.box_wifi.setGeometry(QtCore.QRect(340, 130, 111, 31))
        self.box_wifi.setObjectName(_fromUtf8("box_wifi"))
        self.s_title = QtGui.QLabel(self.search)
        self.s_title.setGeometry(QtCore.QRect(220, 10, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(33)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.s_title.setFont(font)
        self.s_title.setAlignment(QtCore.Qt.AlignCenter)
        self.s_title.setObjectName(_fromUtf8("s_title"))
        self.line_2.raise_()
        self.s_arrdt.raise_()
        self.box_velib.raise_()
        self.s_go.raise_()
        self.box_tournages.raise_()
        self.box_wifi.raise_()
        self.s_title.raise_()
        self.introduction = QtGui.QWidget(self.centralwidget)
        self.introduction.setEnabled(True)
        self.introduction.setGeometry(QtCore.QRect(140, 240, 801, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.introduction.setFont(font)
        self.introduction.setAutoFillBackground(False)
        self.introduction.setObjectName(_fromUtf8("introduction"))
        self.i_slogan = QtGui.QLabel(self.introduction)
        self.i_slogan.setGeometry(QtCore.QRect(350, -10, 461, 121))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Junicode"))
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.i_slogan.setFont(font)
        self.i_slogan.setTextFormat(QtCore.Qt.AutoText)
        self.i_slogan.setScaledContents(False)
        self.i_slogan.setObjectName(_fromUtf8("i_slogan"))
        self.i_title = QtGui.QLabel(self.introduction)
        self.i_title.setGeometry(QtCore.QRect(10, 0, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(33)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.i_title.setFont(font)
        self.i_title.setAlignment(QtCore.Qt.AlignCenter)
        self.i_title.setObjectName(_fromUtf8("i_title"))
        self._iseparator = QtGui.QFrame(self.introduction)
        self._iseparator.setGeometry(QtCore.QRect(310, -10, 16, 121))
        self._iseparator.setFrameShape(QtGui.QFrame.VLine)
        self._iseparator.setFrameShadow(QtGui.QFrame.Sunken)
        self._iseparator.setObjectName(_fromUtf8("_iseparator"))
        self.pushButton_2 = QtGui.QPushButton(self.introduction)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 160, 141, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.i_slogan.raise_()
        self.i_title.raise_()
        self._iseparator.raise_()
        self.search.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuQuitter = QtGui.QMenu(self.menubar)
        self.menuQuitter.setObjectName(_fromUtf8("menuQuitter"))
        self.menuAide = QtGui.QMenu(self.menubar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.action_propos = QtGui.QAction(MainWindow)
        self.action_propos.setObjectName(_fromUtf8("action_propos"))
        self.actionEffectuer_une_recherche = QtGui.QAction(MainWindow)
        self.actionEffectuer_une_recherche.setObjectName(_fromUtf8("actionEffectuer_une_recherche"))
        self.actionLicence = QtGui.QAction(MainWindow)
        self.actionLicence.setObjectName(_fromUtf8("actionLicence"))
        self.actionAccueil = QtGui.QAction(MainWindow)
        self.actionAccueil.setObjectName(_fromUtf8("actionAccueil"))
        self.menuQuitter.addAction(self.actionAccueil)
        self.menuQuitter.addAction(self.actionEffectuer_une_recherche)
        self.menuQuitter.addSeparator()
        self.menuQuitter.addAction(self.actionQuitter)
        self.menuAide.addAction(self.action_propos)
        self.menuAide.addAction(self.actionLicence)
        self.menubar.addAction(self.menuQuitter.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuitter, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.actionEffectuer_une_recherche, QtCore.SIGNAL(_fromUtf8("activated()")),
                               self.introduction.close)
        QtCore.QObject.connect(self.actionAccueil, QtCore.SIGNAL(_fromUtf8("activated()")), self.introduction.show)
        QtCore.QObject.connect(self.actionEffectuer_une_recherche, QtCore.SIGNAL(_fromUtf8("activated()")),
                               self.search.show)
        QtCore.QObject.connect(self.actionAccueil, QtCore.SIGNAL(_fromUtf8("activated()")), self.search.close)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.search.show)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.introduction.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Movies\'n\'Go", None))
        self.box_velib.setText(_translate("MainWindow", "Velib", None))
        self.s_go.setText(_translate("MainWindow", "GO !!", None))
        self.box_tournages.setText(_translate("MainWindow", "Lieux de tournages", None))
        self.box_wifi.setText(_translate("MainWindow", "Wi-Fi", None))
        self.s_title.setText(_translate("MainWindow", "Movies\'n\'Go", None))
        self.i_slogan.setText(_translate("MainWindow", "Trouvez le lieu de tournage qui vous ressemble !", None))
        self.i_title.setText(_translate("MainWindow", "Movies\'n\'Go", None))
        self.pushButton_2.setText(_translate("MainWindow", "Chercher", None))
        self.menuQuitter.setTitle(_translate("MainWindow", "Options", None))
        self.menuAide.setTitle(_translate("MainWindow", "Aide ?", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter", None))
        self.action_propos.setText(_translate("MainWindow", "À propos", None))
        self.actionEffectuer_une_recherche.setText(_translate("MainWindow", "Effectuer une recherche", None))
        self.actionLicence.setText(_translate("MainWindow", "Licence", None))
        self.actionAccueil.setText(_translate("MainWindow", "Accueil", None))

